name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build with Hugo
        run: |
          npm run build
          mkdir -p public
          cp -r .build/* public/
          # Copy NGO page content to root index.html and fix URLs
          cp public/landing/NGO/index.html public/index.html
          # Fix URLs in the root index.html
          sed -i 's|http://localhost:1313/|/|g' public/index.html
          sed -i 's|/landing/NGO/|/|g' public/index.html
          # Fix asset paths
          sed -i 's|/Logo-Uxess/|/Logo-Uxess/|g' public/index.html
          sed -i 's|/app.css|/app.css|g' public/index.html
          sed -i 's|/app.js|/app.js|g' public/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 