name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build with Hugo
        run: |
          npm run build
          mkdir -p public
          cp -r .build/* public/
          # Debug: List contents of public directory
          echo "Contents of public directory:"
          ls -la public/
          # Create a test index.html
          cat > public/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>UXESS Accessibility</title>
              <meta http-equiv="refresh" content="0;url=/blog/landing/NGO/">
          </head>
          <body>
              <h1>Redirecting to UXESS Accessibility...</h1>
              <p>If you are not redirected automatically, <a href="/blog/landing/NGO/">click here</a>.</p>
          </body>
          </html>
          EOL
          # Debug: Check if index.html exists
          echo "Checking if index.html exists:"
          ls -la public/index.html
          # Debug: Show first few lines of index.html
          echo "First few lines of index.html:"
          head -n 5 public/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 