name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          echo "Installing npm dependencies..."
          npm install
          echo "npm dependencies installed successfully"

      - name: Build with Hugo
        run: |
          echo "Starting build process..."
          
          # Create public directory
          mkdir -p public
          echo "Created public directory"
          
          # Run npm build
          echo "Running npm build..."
          npm run build || {
            echo "npm build failed"
            exit 1
          }
          echo "npm build completed successfully"
          
          # List contents of .build directory
          echo "Contents of .build directory:"
          ls -la .build/
          
          # Copy all files from .build to public
          echo "Copying files to public directory..."
          cp -r .build/* public/ || {
            echo "Failed to copy files to public directory"
            exit 1
          }
          echo "Files copied successfully"
          
          # Create landing page (root index.html)
          if [ -f "public/landing/NGO/index.html" ]; then
            echo "Creating landing page..."
            cp public/landing/NGO/index.html public/index.html
            # Fix URLs in the landing page
            sed -i 's|http://localhost:1313/|/|g' public/index.html
            sed -i 's|/landing/NGO/|/|g' public/index.html
            echo "Landing page created successfully"
          else
            echo "Error: public/landing/NGO/index.html not found"
            exit 1
          fi
          
          # Debug: List contents of public directory
          echo "Final contents of public directory:"
          ls -la public/
          echo "Contents of index.html:"
          head -n 5 public/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 